spring:
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true       #如果没有找到handler则会抛出异常，进行404捕获使用
  resources:
    add-mappings: false                             #不启用默认的错误页
server:
  port: 9999
